# Generated by Django 3.2.9 on 2023-07-24 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211113_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='カテゴリ名')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='スラッグ')),
            ],
            options={
                'verbose_name': 'カテゴリ',
                'verbose_name_plural': 'カテゴリ',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='商品名')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='スラッグ')),
                ('image', models.ImageField(default='photos/default.jpg', upload_to='photos/products')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='商品説明')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='価格')),
                ('in_stock', models.BooleanField(default=True, verbose_name='在庫あり')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.category')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'ordering': ('-created_at',),
            },
        ),
    ]
