# Generated by Django 3.2.9 on 2023-08-07 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='recommend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='sales_discount',
            field=models.BooleanField(default=False),
        ),
    ]
