# Generated by Django 3.2.9 on 2023-08-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20230811_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ranking',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
